name: Test PostgreSQL personnalisÃ©

on: push

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      db:
        image: henriteinturier/postgres-init:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ðŸ› ï¸ Installer le client PostgreSQL (psql)
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: ðŸ§ª Lister les utilisateurs dans la base PostgreSQL
        run: |
          echo "Connexion Ã  la base PostgreSQL..."
          psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "SELECT * FROM users;"
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: ðŸ’¾ Dump de la base PostgreSQL
        run: |
          mkdir -p dumps
          pg_dump -h db -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} > dumps/dump.sql
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      - name: ðŸ“¤ Upload du dump PostgreSQL comme artefact
        uses: actions/upload-artifact@v4
        with:
          name: dump-postgres
          path: dumps/dump.sql
