name: Test PostgreSQL personnalis√©

on: push

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      db:
        image: henriteinturier/postgres-init:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: üõ†Ô∏è Installer le client PostgreSQL (psql)
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: üß™ Lister les utilisateurs dans la base PostgreSQL
        run: |
          echo "Connexion √† la base PostgreSQL..."
          psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "SELECT * FROM users;"
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
